"""Create affiliates table

Revision ID: c5303f1d2148
Revises: add_fraud_alert_models
Create Date: 2025-09-18 18:08:22.577240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5303f1d2148'
down_revision = 'add_fraud_alert_models'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'suspended', 'inactive', name='affiliate_status'), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=False),
    sa.Column('referrals', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_media', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('performance', sa.Enum('excellent', 'good', 'poor', 'new', name='affiliate_performance'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliates')
    # ### end Alembic commands ###
