"""Create user_referrals table

Revision ID: create_user_referrals
Revises: c5303f1d2148
Create Date: 2025-01-18 22:31:27.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'create_user_referrals'
down_revision = 'c5303f1d2148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('referred_at', sa.DateTime(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=True),
    sa.Column('conversion_amount', sa.Float(), nullable=True),
    sa.Column('commission_earned', sa.Float(), nullable=True),
    sa.Column('referral_source', sa.String(length=100), nullable=True),
    sa.Column('referral_medium', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_referrals_affiliate_id'), 'user_referrals', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_user_referrals_user_id'), 'user_referrals', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_referrals_coupon_code'), 'user_referrals', ['coupon_code'], unique=False)
    op.create_index(op.f('ix_user_referrals_is_converted'), 'user_referrals', ['is_converted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_referrals_is_converted'), table_name='user_referrals')
    op.drop_index(op.f('ix_user_referrals_coupon_code'), table_name='user_referrals')
    op.drop_index(op.f('ix_user_referrals_user_id'), table_name='user_referrals')
    op.drop_index(op.f('ix_user_referrals_affiliate_id'), table_name='user_referrals')
    op.drop_table('user_referrals')
    # ### end Alembic commands ###